package com.nwl.lanya.po;

/**
 * @author misaki
 */
public class Addmanage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addmanage.id
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addmanage.img_url
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addmanage.img_intro
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private String imgIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addmanage.id
     *
     * @return the value of addmanage.id
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addmanage.id
     *
     * @param id the value for addmanage.id
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addmanage.img_url
     *
     * @return the value of addmanage.img_url
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addmanage.img_url
     *
     * @param imgUrl the value for addmanage.img_url
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addmanage.img_intro
     *
     * @return the value of addmanage.img_intro
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public String getImgIntro() {
        return imgIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addmanage.img_intro
     *
     * @param imgIntro the value for addmanage.img_intro
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setImgIntro(String imgIntro) {
        this.imgIntro = imgIntro == null ? null : imgIntro.trim();
    }
}