package com.nwl.lanya.po;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_img
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private String courseImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_title
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private String courseTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_intro
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private String courseIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_score
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private Double courseScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_url
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private String courseUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.is_visible
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    private Integer isVisible;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_img
     *
     * @return the value of course.course_img
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public String getCourseImg() {
        return courseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_img
     *
     * @param courseImg the value for course.course_img
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setCourseImg(String courseImg) {
        this.courseImg = courseImg == null ? null : courseImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_title
     *
     * @return the value of course.course_title
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public String getCourseTitle() {
        return courseTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_title
     *
     * @param courseTitle the value for course.course_title
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setCourseTitle(String courseTitle) {
        this.courseTitle = courseTitle == null ? null : courseTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_intro
     *
     * @return the value of course.course_intro
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public String getCourseIntro() {
        return courseIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_intro
     *
     * @param courseIntro the value for course.course_intro
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setCourseIntro(String courseIntro) {
        this.courseIntro = courseIntro == null ? null : courseIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_score
     *
     * @return the value of course.course_score
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public Double getCourseScore() {
        return courseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_score
     *
     * @param courseScore the value for course.course_score
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setCourseScore(Double courseScore) {
        this.courseScore = courseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_url
     *
     * @return the value of course.course_url
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public String getCourseUrl() {
        return courseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_url
     *
     * @param courseUrl the value for course.course_url
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setCourseUrl(String courseUrl) {
        this.courseUrl = courseUrl == null ? null : courseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.is_visible
     *
     * @return the value of course.is_visible
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public Integer getIsVisible() {
        return isVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.is_visible
     *
     * @param isVisible the value for course.is_visible
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    public void setIsVisible(Integer isVisible) {
        this.isVisible = isVisible;
    }
}