package com.nwl.lanya.po;

public class LabelInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_info.id
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_info.label_name
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    private String labelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_info.label_code
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    private String labelCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_info.id
     *
     * @return the value of label_info.id
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_info.id
     *
     * @param id the value for label_info.id
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_info.label_name
     *
     * @return the value of label_info.label_name
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_info.label_name
     *
     * @param labelName the value for label_info.label_name
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_info.label_code
     *
     * @return the value of label_info.label_code
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    public String getLabelCode() {
        return labelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_info.label_code
     *
     * @param labelCode the value for label_info.label_code
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    public void setLabelCode(String labelCode) {
        this.labelCode = labelCode == null ? null : labelCode.trim();
    }
}