package com.nwl.lanya.dao;

import com.nwl.lanya.dto.AddManageDto;
import com.nwl.lanya.po.Addmanage;
import com.nwl.lanya.po.AddmanageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddmanageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    long countByExample(AddmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    int deleteByExample(AddmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    int insert(Addmanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    int insertSelective(Addmanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    List<Addmanage> selectByExample(AddmanageExample example);

    /**
     * 展示列表数据
     * @param dto 传输对象
     * @return AddManage对象列表
     */
    List<Addmanage> list(AddManageDto dto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    Addmanage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") Addmanage record, @Param("example") AddmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    int updateByExample(@Param("record") Addmanage record, @Param("example") AddmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    int updateByPrimaryKeySelective(Addmanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addmanage
     *
     * @mbg.generated Thu Mar 04 10:08:32 CST 2021
     */
    int updateByPrimaryKey(Addmanage record);

    /**
     * 统计表数据量
     * @return 表数据量
     */
    long countByList();

}