package com.nwl.lanya.dao;

import com.nwl.lanya.dto.LabelInfoDto;
import com.nwl.lanya.po.LabelInfo;
import com.nwl.lanya.po.LabelInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LabelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    long countByExample(LabelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    int deleteByExample(LabelInfoExample example);

    /**
     * 分页标签列表
     *
     * @param dto 标签传输对象
     * @return 标签列表
     */
    List<LabelInfo> list(LabelInfoDto dto);

    /**
     * 统计标签数
     *
     * @param dto
     * @return 标签数
     */
    Long countByList(LabelInfoDto dto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    int insert(LabelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    int insertSelective(LabelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    List<LabelInfo> selectByExample(LabelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    LabelInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    int updateByExampleSelective(@Param("record") LabelInfo record, @Param("example") LabelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    int updateByExample(@Param("record") LabelInfo record, @Param("example") LabelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    int updateByPrimaryKeySelective(LabelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_info
     *
     * @mbg.generated Thu Mar 04 12:51:26 CST 2021
     */
    int updateByPrimaryKey(LabelInfo record);

    /**
     * 获取热点标签
     * @return
     */
    List<LabelInfo> selectHotLabels();
}